Add support for start_mode
stevearc/dressing.nvim pull request #175
Opened 2024-10-25 15:42 UTC by MarcelRobitaille

Implement `start_mode`. It's like `start_in_insert`, but more flexible.

## Context

Implement #174 

## Description

I added `start_mode`. I kept `start_in_insert` for backwards compatibility.

## Test Plan

I tried each value of `start_mode` with a default value and without. I also added automated tests of the backwards compatibility of `start_in_insert`.

2024-10-25 15:51 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> -    start_in_insert = context.start_in_insert
This seemed unnecessary to me, but maybe I'm missing something

2024-10-25 16:24 UTC, stevearc requested changes
Left some comments. Also make sure that as you're testing this you test different combinations of your starting mode + the `start_mode` option. For example, try running vim.ui.input when you're already in visual mode and with `start_mode = "insert"`. Try that for all the permutations to make sure that the `start_mode` is respected in all cases and there's no weirdness.

2024-10-25 16:24 UTC, stevearc commented on lua/dressing/config.lua
> +    start_mode = "insert",
Can we provide a list of accepted values in the comment?
```suggestion
    -- The initial mode when the window opens (insert|visual|normal)
    start_mode = "insert",
```

2024-10-25 16:24 UTC, stevearc commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
Would be great to also provide support for select mode (see `:help Select-mode`)

2024-10-25 16:24 UTC, stevearc commented on lua/dressing/input.lua
> -    start_in_insert = context.start_in_insert
If you're not sure what something is used for, look at the git blame for the lines
https://github.com/stevearc/dressing.nvim/blame/1b7921eecc65af1baf8ac1dc06f0794934cbcfb2/lua/dressing/input.lua#L108-L110

That will take you to 25b72621af45b5f457382b9aded7ee6b1c80b427, which will tell you that this is for restoring the previous mode upon closing the modal.

I believe that this is completely unrelated to the `config.start_in_insert` option and is just an unfortunate name collision.

2024-10-25 16:24 UTC, stevearc commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
For backwards compatibility, I like to put the shims in the `config.update` function that translate the old value when provided (`start_in_insert`) into the new value (`start_mode`). That way all the shims live in one place and the rest of the code can just use the most recent config shape.

2024-10-25 16:24 UTC, stevearc commented on lua/dressing/input.lua
> +     vim.api.nvim_command("normal! v$h")
Can you clarify what is happening when you say it "doesn't work well"?

2024-10-25 16:44 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +     vim.api.nvim_command("normal! v$h")
> Can you clarify what is happening when you say it "doesn't work well"?

@stevearc I can't comment on your other comment for some reason, so I will answer here.
I first tried just `v$`, but it selected too much. It looked like the cursor was beyond the end of the string. When I pressed <kbd>A</kdb>, the cursor went just before the last character, not after it.

![image](https://github.com/user-attachments/assets/a0dc4538-57dd-419f-aff1-b380c478d362)
After pressing <kbd>A</kbd>
![image](https://github.com/user-attachments/assets/97f0104b-2f22-4773-b65a-14eb70c622aa)

2024-10-25 16:50 UTC, MarcelRobitaille commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Sounds good. BTW do you think I should show a warning / error if you specify both `start_in_insert` and `start_mode`?

2024-10-25 16:59 UTC, stevearc commented on lua/dressing/input.lua
> +     vim.api.nvim_command("normal! v$h")
Interesting. You could try using `g_` instead of `$`?

2024-10-25 17:00 UTC, stevearc commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Eh, probably not right now. I think just providing a shim is fine for right now, then after some time I'll add a deprecation message for `start_in_insert`.

2024-10-25 21:30 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
Do you know a good way to get into select mode? The best option to me reading the help is `CTRL-G` since it doesn't require changing any settings, but it's not working for me. It works if I do it manually (set `start_mode` to visual and press `CTRL-G`) but not using
```lua
    vim.api.nvim_command("normal! v$")
    local ctrl_g = vim.api.nvim_replace_termcodes("<C-g>", true, false, true)
    vim.api.nvim_feedkeys(ctrl_g, "v", true)

```

2024-10-25 21:33 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +     vim.api.nvim_command("normal! v$h")
<kbd>g_</kbd> works. Thanks!

2024-10-25 21:38 UTC, MarcelRobitaille commented
Thanks for the quick review. I addressed some of the comments. I left some to do because I'd like some feedback first.

2024-10-26 00:24 UTC, stevearc commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
This seems to work for me
```lua
vim.cmd("normal! 0vg_")
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-g>", true, false, true), "n", true)
```

2024-10-26 00:41 UTC, stevearc commented
Only question you were waiting on was about select mode, right?

2024-10-26 08:28 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
This snippet puts me in visual mode. Shouldn't it be `"v"`, not `"n"`? I thought it was a visual mode mapping.

2024-10-26 08:30 UTC, MarcelRobitaille commented
Yes unless you also want to have a look at how I added back restoring the previous mode.

2024-10-26 08:47 UTC, MarcelRobitaille commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
I think `config.update` does not get triggered for `get_config`. If someone configures `start_in_insert` in `get_config`, it won't get translated.

2024-10-27 16:59 UTC, stevearc requested changes

2024-10-27 16:59 UTC, stevearc commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Ah, good point. That logic happens in `config.get_mod_config`
https://github.com/stevearc/dressing.nvim/blob/1b7921eecc65af1baf8ac1dc06f0794934cbcfb2/lua/dressing/config.lua#L176-L186

You could make a simple shim function and call it from both `update` and `get_mod_config`

2024-10-27 16:59 UTC, stevearc commented on lua/dressing/input.lua
> +  set_mode(ctx.restore_mode)
This isn't what we want for restoring the mode. `startinsert!` will position the cursor at the end of the line instead of where it was previously, visual and select will select the entire rest of the line instead of the previous range.

FWIW, I wouldn't worry too much about restoring visual or select mode. Nobody has asked for that so far, so I believe it is relatively uncommon. We mainly just want to cover normal mode and insert mode here.

2024-10-27 16:59 UTC, stevearc commented on lua/dressing/input.lua
> +    restore_mode = ({ i = "insert", n = "normal", v = "visual", s = "select" })[mode_chr]
If you get the mode this way you'll have to handle when it is `nil`

2024-10-28 16:40 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +    restore_mode = ({ i = "insert", n = "normal", v = "visual", s = "select" })[mode_chr]
I thought it was allowed to be `nil`. The return value reflects that at least.

2024-10-28 17:54 UTC, stevearc commented on lua/dressing/input.lua
> +    restore_mode = ({ i = "insert", n = "normal", v = "visual", s = "select" })[mode_chr]
Ah, you're right that the return value accounts for this. It looks like the issue is that elsewhere the types are not being checked as strictly as I would expect. For example, line 134
```lua
set_mode(ctx.restore_mode)
```
set_mode requires it to be non-nil, but `ctx.restore_mode` is nilable.

It's not super important to get all of that working perfectly. It's not like it's any worse than before.

2024-10-29 13:50 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +    restore_mode = ({ i = "insert", n = "normal", v = "visual", s = "select" })[mode_chr]
I'll just make `set_mode` take an optional. It just checks the mode against some strings. If it's `nil`, then it will do nothing.

2024-10-29 22:12 UTC, MarcelRobitaille commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Done. Is that what you had in mind?

2024-10-29 22:12 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +  set_mode(ctx.restore_mode)
I gave it a shot. Is that what you meant? Note that `set_mode` is still incomplete.

2024-10-29 22:13 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
I'm still not sure what to do here.

2024-10-30 03:28 UTC, stevearc requested changes

2024-10-30 03:28 UTC, stevearc commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Yes, but there is a bug. The way `get_config` works is it returns the config options for just that key. So for example:

```lua
require("dressing").setup({
  input = {
    start_mode = "normal",
    get_config = function(opts)
      return {
        start_mode = "visual"
      }
    }
  }
})
```

So `apply_shim` will need to operate on these sub-object configs instead of the whole config object if it's going to work with `get_config`.

2024-10-30 03:28 UTC, stevearc commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
I just tried the snippet that I gave you on your branch and it works for me. Are you sure that it's not working? Is it possible that something else in your config is interfering with it?

2024-10-30 08:15 UTC, MarcelRobitaille commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
You mean sub-objects like `input`. Doesn't it already operate on these sub-objects? I tested it like this:
```lua
   input = {
      start_mode = "insert",
      get_config = function(opts)
         return {
            start_in_insert = false,
         }
      end,
   },
```
And I start in normal mode.

2024-10-30 09:37 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +---@alias dressing.StartMode "insert" | "visual" | "normal"
You're right. I just tried this, and I got into select mode.
```
nvim -u NORC --noplugin -c 'lua vim.cmd("normal! 0vg_")' -c 'lua vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-g>", true, false, true), "n", true)'
```

2024-10-30 15:50 UTC, stevearc requested changes
This looks good. Once you add support for select mode and fix the CI, it's good to merge!

2024-10-30 15:50 UTC, stevearc commented on lua/dressing/input.lua
>  ---@field start_in_insert? boolean
Oh man I misread it, apologies! My code reviews at the end of the day are not at the top of my game 😅

2024-10-30 23:47 UTC, stevearc requested changes
Still some CI failures

2024-10-31 17:03 UTC, MarcelRobitaille commented
I'm having some trouble with the tests. I saw some comments that `startinsert` doesn't work in tests, but even if I do `util.feedkeys({"i"})`, `vim.api.nvim_get_mode().mode` always says it's in normal mode. Is it not possible to change the mode at all in tests? I'm new to this headless neovim testing.

2024-10-31 23:29 UTC, stevearc commented
Headless testing isn't great; as you've discovered there are some difficult inconsistencies to deal with. Unfortunately I don't have any better idea what hacks will help bypass this. Just try a few things, see if you can get something working, and if not no worries I won't block the PR for lack of tests.

2024-11-01 23:20 UTC, MarcelRobitaille commented
Since insert mode doesn't work well, I mocked `set_mode` and `restore_mode`.

2024-11-02 17:26 UTC, stevearc requested changes
One nit and still some styling inconsistencies

2024-11-02 17:26 UTC, stevearc commented on lua/dressing/input.lua
> +  if mode == "normal" then
I think we should do
```suggestion
  if mode ~= "insert" then
```
I think the default should be going back to normal mode, and only restore insert if we started in insert

2024-11-03 09:54 UTC, MarcelRobitaille commented on lua/dressing/input.lua
> +  if mode == "normal" then
In this case, nil also stops insert. Is that desired?

2024-11-03 20:06 UTC, stevearc commented on lua/dressing/input.lua
> +  if mode == "normal" then
Yeah, I think that we have a good idea how to restore insert mode (you just go back to insert mode), but any other mode not so much. I think that it makes more sense for any given mode to be returned to normal mode than to insert mode. For example, if I started in visual mode I would be surprised if after a `vim.ui.input` I found myself in insert mode.

2024-11-03 20:19 UTC, stevearc commented
Great job! Thanks for the PR!

2024-11-03 20:20 UTC, merged

2024-11-03 20:21 UTC, MarcelRobitaille commented
No, thank you! I really appreciate how patient you were with me.