feat: allow to pass extra opts to vim.keymap.set()
stevearc/dressing.nvim pull request #83
Opened 2023-02-01 18:10 UTC by uga-rosa

Allow additional opts to be passed to vim.keymap.set().

## Context

I want to pass `{ nowait = true }`.

## Description

Allow additional opts to be passed to vim.keymap.set().

## Test Plan

Define an nmap that begins with `<Esc>` as follows, and pass `{ nowait = true }` to see if the delay exists.

`nnoremap <Esc><Esc> <Cmd>nohl<CR>`

2023-02-03 06:00 UTC, stevearc requested changes
I don't like that this API passes extra arguments to _all_ of the keymaps. Honestly the mapping logic could use a refactor, but until I get to it you could change the utility to accept a table. For example:
```lua
require("dressing").setup({
  input = {
    mappings = {
      n = {
        ["<Esc>"] = {"Close", nowait = true},
        ["<CR>"] = "Confirm",
      }
    }
  }
})
```

2023-02-03 13:10 UTC, uga-rosa commented
How about this?

2023-02-04 20:42 UTC, stevearc requested changes

2023-02-04 20:42 UTC, stevearc commented on lua/dressing/map_util.lua
> +        opts = vim.tbl_extend(opts, r)
This will crash because `vim.tbl_extend` requires a behavior to be its first argument. It should be `opts = vim.tbl_extend("force", opts, r)`.

Always test your code to make sure it works :)

2023-02-05 17:20 UTC, uga-rosa commented on lua/dressing/map_util.lua
> +        opts = vim.tbl_extend(opts, r)
Sorry. I fixed.

2023-02-05 19:43 UTC, stevearc approved these changes

2023-02-05 19:43 UTC, stevearc commented
Thanks for the PR!

2023-02-05 19:43 UTC, merged